echo -- 4NORWAY NorESM2-MM downscaling Norway using WRF model: Run this on NIRD --
if [ -z "$1" ]; then
    echo Error: Requires YEAR as argument.
    exit
fi 
# Use $IM work folder:
year=$1
user=$USER
proj=4NORWAY-WRF

nird_work=/scratch/$user/$proj
fram_work=/cluster/work/users/$user/$proj
betzy_work=/cluster/work/users/$user/$proj
IM=IM_NorESM
into_ncl=${year}_intoNCL

fram=login-1.fram.sigma2.no
betzy=login-2.betzy.sigma2.no


echo -- 1. NIRD: Clean old and extract variables and create $IM variables...
# Output: NIRD: /scratch/tylo/noresm2-wrf/$IM/1984_intoNCL/atmos_hus.nc ...
echo \rm -ir $nird_work/$IM/????_intoNCL
echo python Extract_Vars_RF.py $year $nird_work/$IM

echo -- 2. NIRD: copy files generated by Extact_Vars_RF.py to FRAM:
# Output: FRAM: /cluster/work/users/tylo/noresm2-wrf/$IM/1984_intoNCL/atmos_hus.nc ...
# NOT NEEDED echo ssh $user@$fram mkdir -p $fram_work/$IM/$into_ncl
echo scp -r $nird_work/$IM/$into_ncl $user@$fram:$fram_work/$IM # TODO: TEST

echo -- 3. FRAM: Submit Hybrid_To_Pres_new.ncl script:
# Input:  FRAM: /cluster/work/users/tylo/noresm2-wrf/IM_NorESM/1984_intoNCL/atmos_hus.nc ...
# Output: FRAM: /cluster/work/users/tylo/noresm2-wrf/IM_NorESM/1984/NorESM2-MM:1984-01-01_00
echo scp Hybrid_To_Pres_new.ncl submit2queue.sh $user@$fram:$fram_work/$IM/
echo ssh $user@$fram "cd $fram_work/$IM ; sbatch submit2queue.sh $year $fram_work/$IM/"

echo -- 4. FRAM: Copy output from NCL-script to BETZY:
# Input:  FRAM:  /cluster/work/users/tylo/noresm2-wrf/IM_NorESM/OUTPUT_HIST/1984/
# Output: BETZY: /cluster/work/users/tylo/noresm2-wrf/IM_NorESM/1984/NorESM2-MM:1984-01-01_00
echo ssh $user@$betzy mkdir -p $betzy_work/$IM
echo scp -3 -r $user@$fram:$fram_work/$IM/OUTPUT_HIST/$year $user@$betzy:$betzy_work/$IM/

echo -- 5. BETZY: run metgrid.exe
# Input:  namelist.wps, geo_em.d01, geo_em.d02
# Output: met_em.DOMAIN.YYYY-MM-DD...
#echo scp iompi-2020b/wps/ $user@$betzy:run_metgrid.sh
echo ssh $user@$betzy sbatch $betzy_work/run_metgrid.sh  # Todo

echo -- 6. BETZY: Run real.exe
# Input:  namelist.input, met_em*
# Output:wrfbdy_d01,wrfinput_d01, wrfbdy_d02,wrfinput_d02
echo ssh $user@$betzy sbatch $betzy_work/run_wrf.sh  # Needs SBATCH tuning

echo -- 7. BETZY: Run wrf.exe
# Input:namelist.input, wrfbdy_d01,wrfinput_d01, wrfbdy_d02,wrfinput_d02
echo ssh $user@$betzy sbatch $betzy_work/run_wrf.sh  # Needs SBATCH tuning
