echo -- NorESM2-MM downscaling Norway: Run this on NIRD --
if [ -z "$1" ]; then
    echo Error: Requires YEAR as argument.
    exit
fi 
# Use IM_NorESM work folder:
year=$1
user=$USER
proj=noresm2-mm

nird_work=/scratch/$user/$proj
fram_work=/cluster/work/users/$user/$proj
betzy_work=/cluster/work/users/$user/$proj

fram=login-1.fram.sigma2.no
betzy=login-2.betzy.sigma2.no
ncl_out=IM_NorESM/OUTPUT_HIST


echo -- 1. NIRD: Remove any existing IM_NorESM datasets prepared for NCL before generating the new...
echo rm -r $nird_work/IM_NorESM/????_intoNCL

echo -- 2. NIRD: extract variables and create IM_NorESM variables...
# Output: /scratch/tylo/noresm2-mm/IM_NorESM/1984_intoNCL/atmos_hus.nc ...
echo python Extract_Vars_RF.py $year $nird_work/IM_NorESM

echo -- 3. NIRD: copy files generated by Extact_Vars_RF.py to FRAM:
echo ssh $user@$fram mkdir -p $fram_work/IM_NorESM
echo scp -r $nird_work/IM_NorESM $user@$fram:$fram_work/IM_NorESM

echo -- 4. NIRD: Copy the NCL script to FRAM:
scp Hybrid_To_Pres_new.ncl submit2queue.sh $user@$fram:$fram_work/IM_NorESM/

echo -- 5. FRAM: Submit Hybrid_To_Pres_new.ncl script:
# Input:  /cluster/work/users/tylo/noresm2-mm/IM_NorESM/1984_intoNCL/atmos_hus.nc ...
# Output: /cluster/work/users/tylo/noresm2-mm/IM_NorESM/1984/NorESM2-MM:1984-01-01_00
echo ssh $user@$fram sbatch $fram_work/IM_NorESM/submit2queue.sh $year $fram_work/IM_NorESM/

echo -- 6. FRAM: Copy NCL-script output to BETZY: $fram_work/$ncl_out
# Output: /cluster/work/users/tylo/noresm2-mm/IM_NorESM/1984/NorESM2-MM:1984-01-01_00
scp -3 -r $user@$fram:$fram_work/$ncl_out/$year $user@$fram:$betzy_work/$ncl_out/

echo -- 7. BETZY: run metgrid.exe
# Input: namelist.wps, geo_em.d01, geo_em.d02
# Output: met_em.DOMAIN.YYYY-MM-DD...
echo ssh sbatch $user@$betzy run_metgrid.sh
echo ssh $user@$betzy sbatch $betzy_work/run_metgrid.sh  # Todo

echo -- 8. BETZY: Run real.exe
# Input: namelist.input, met_em*
# Output:wrfbdy_d01,wrfinput_d01, wrfbdy_d02,wrfinput_d02
echo ssh $user@$betzy sbatch $betzy_work/run_wrf.sh  # Needs SBATCH tuning

echo -- 9. BETZY: Run wrf.exe
# Input:namelist.input, wrfbdy_d01,wrfinput_d01, wrfbdy_d02,wrfinput_d02
echo ssh $user@$betzy sbatch $betzy_work/run_wrf.sh  # Needs SBATCH tuning
